pipeline{
    agent any

    parameters {
        booleanParam(name: 'deploy', defaultValue: false, description: 'choose to deploy on dockerhub')
        choice(name: 'Test_tool', choices: ['docker-compose', 'kubernetes'], description: 'For testing use dcoker-compose')
    }
    environment {
        DB_CREDENTIALS = credentials('DB_CREDENTIALS')
        DB_NAME = credentials('DB_NAME')
        DOCKER_CREDENTIALS = credentials('DOCKER_CREDENTIALS')
    }
    stages{
        stage('build') {
            steps {
                echo '****************************************'
                echo '***building the frontend docker image***'
                echo '****************************************'
                dir ('frontend') {
                    sh "docker build -t frontend:$BUILD_NUMBER ."
                }
            }
        }
        stage('test') {
            when{
                expression {
                    return ("${params.Test_tool}" == 'docker-compose')
                }
            }
            steps {
                echo '***running backend and frontend in docker-compose for testing***'
                sh 'docker-compose -f docker-compose.yml up --build --abort-on-container-exit'
            }
        }
    }
}