version: "3.8"

services:
  web:
    image: "frontend:${BUILD_NUMBER}"
    environment:
      - INTERNAL_BACKEND_URL=http://api:3001/api/
    command: nginx_config/templating_script.sh
  api:
    build: ./backend
    environment:
      - DB_USER="${DB_CREDENTIALS_USR}"
      - DB_PASSWORD="${DB_CREDENTIALS_PSW}"
      - DB_NAME=${DB_NAME}
    command: /app/docker-entrypoint.sh

