version: "3.8"

services:
  web:
    image: frontend:$BUILD_NUMBER
    ports:
      - "3000:3000"
     # - "80:80"
    environment:
      - INTERNAL_BACKEND_URL=http://api
      - INTERNAL_BACKEND_PORT=3001
    # command: nginx_config/templating_script.sh
  api:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_USER=$DB_CREDENTIALS_USR
      - DB_PASSWORD=$DB_CREDENTIALS_PSW
      - DB_NAME=$DB_NAME
    command: /app/docker-entrypoint.sh

