version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 80:80
    environment:
      - INTERNAL_BACKEND_URL=http://localhost:3001/api/
      - REACT_APP_API_URL=/api/

  api:
    build: ./backend
    ports:
      - 3001:3001
    env_file:
      - /home/ansible/vidly-working/vidly1/backend/backend.env
    command: /app/docker-entrypoint.sh
#   db:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     volumes:
#       - vidly:/data/db

# volumes:
#   vidly:
